name: Classify and Patch Vulnerable Dependencies

on:
  workflow_dispatch:

jobs:
  classify-and-patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Vulnerabilities
        id: fetch_vulnerabilities
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          QUERY=$(cat <<'EOF'
          {
            "query": "query ($org: String = \"\", $repo: String! = \"\") { organization(login: $org) { repository(name: $repo) { name vulnerabilityAlerts(first: 100, states: OPEN) { nodes { dependencyRelationship vulnerableManifestPath securityVulnerability { advisory { ghsaId summary } severity package { name ecosystem } firstPatchedVersion { identifier } vulnerableVersionRange } } } } } }",
            "variables": {
              "org": "${{ github.repository_owner }}",
              "repo": "${{ github.event.repository.name }}"
            }
          }
          EOF
          )
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer $API_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$QUERY" \
            https://api.github.com/graphql)
          echo "$RESPONSE" > vulnerabilities.json
          echo "$RESPONSE" | jq -c '.data.organization.repository.vulnerabilityAlerts.nodes[]' > vulnerabilities_list.json

      - name: Classify Vulnerable Dependencies
        run: |
          gradle dependencies > gradle_dependencies.txt
          gradle buildEnvironment > gradle_build_env.txt

          touch found_in_dependencies.txt
          touch found_in_build_env.txt

          jq -c '.' vulnerabilities_list.json | while read -r vuln; do
            PACKAGE=$(echo "$vuln" | jq -r '.securityVulnerability.package.name')
            if grep -q "$PACKAGE" gradle_dependencies.txt; then
              echo "$vuln" >> found_in_dependencies.txt
            fi
            if grep -q "$PACKAGE" gradle_build_env.txt; then
              echo "$vuln" >> found_in_build_env.txt
            fi
          done

      - name: Patch Vulnerable Dependencies
        run: |
          patch_gradle_transitive() {
            local GROUP=$1
            local ARTIFACT=$2
            local VERSION=$3

            if [ -z "$VERSION" ] || [ "$VERSION" == "null" ]; then
              echo "WARNING: No patched version found for ${GROUP}:${ARTIFACT}, skipping..."
              return 1
            fi

            local PATCH_LINE="force '${GROUP}:${ARTIFACT}:${VERSION}'"

            if grep -q "configurations.all[[:space:]]*{" build.gradle; then
              if grep -A 10 "configurations.all[[:space:]]*{" build.gradle | grep -q "resolutionStrategy[[:space:]]*{"; then
                if grep -q "force[[:space:]]*'${GROUP}:${ARTIFACT}:" build.gradle; then
                  sed -i "s|force[[:space:]]*'${GROUP}:${ARTIFACT}:[^']*'|${PATCH_LINE}|g" build.gradle
                else
                  awk -v patch="$PATCH_LINE" '
                    /resolutionStrategy[[:space:]]*{/ { print; in_block=1; next }
                    in_block && /^\s*}/ { print "        " patch; in_block=0 }
                    { print }
                  ' build.gradle > tmp && mv tmp build.gradle
                fi
              else
                awk -v patch="$PATCH_LINE" '
                  /configurations.all[[:space:]]*{/ {
                    print; print "    resolutionStrategy {"; print "        " patch; print "    }"; next
                  }
                  { print }
                ' build.gradle > tmp && mv tmp build.gradle
              fi
            else
              awk -v patch="$PATCH_LINE" '
                /^dependencies[[:space:]]*{/ {
                  print "configurations.all {";
                  print "    resolutionStrategy {";
                  print "        " patch;
                  print "    }";
                  print "}"; print ""; print $0; next;
                }
                { print }
              ' build.gradle > tmp && mv tmp build.gradle
            fi
          }

          patch_gradle_direct() {
            local GROUP=$1
            local ARTIFACT=$2
            local VERSION=$3
            local TARGET="${GROUP}:${ARTIFACT}"

            if grep -q "${TARGET}:" build.gradle; then
              echo "→ Direct dependency found, replacing version of $TARGET with $VERSION"
              sed -i "s|\"${TARGET}:[^\"]*\"|\"${TARGET}:${VERSION}\"|g" build.gradle
            else
              echo "→ Could not find $TARGET directly in dependencies block. Will patch as transitive instead."
              patch_gradle_transitive "$GROUP" "$ARTIFACT" "$VERSION"
            fi
          }

          for FILE in found_in_dependencies.txt found_in_build_env.txt; do
            if [ -f "$FILE" ]; then
              while read -r entry; do
                PACKAGE=$(echo "$entry" | jq -r '.securityVulnerability.package.name')
                PATCHED_VERSION=$(echo "$entry" | jq -r '.securityVulnerability.firstPatchedVersion.identifier')
                GROUP=$(echo "$PACKAGE" | cut -d':' -f1)
                ARTIFACT=$(echo "$PACKAGE" | cut -d':' -f2)

                echo "Patching ${GROUP}:${ARTIFACT} to version ${PATCHED_VERSION}"
                patch_gradle_direct "$GROUP" "$ARTIFACT" "$PATCHED_VERSION"
              done < "$FILE"
            fi
          done


      - name: Show Final build.gradle
        run: cat build.gradle
